services:
  client:
    build:
      context: . # This should be run from the client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - REACT_APP_API_SOURCE=http://localhost:5001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  server:
    build:
      context: ../AvalonApiNoDB # Path to backend repo Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development